import type { Metadata } from "next";
import { Inter, Lexend, Roboto, Source_Sans_3 } from "next/font/google";
import "./globals.css";
import AuthListener from "@/components/AuthListener";
import GlobalModal from "@/components/GlobalModal";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "500", "700"],
});

const sourceSans3 = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-source-sans-3",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html
      lang="en"
      className={`${lexend.variable} ${inter.variable} ${roboto.variable} ${sourceSans3.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthListener />
        <GlobalModal />
        {children}
      </body>
    </html>
  );
}
